version: '3'

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8080:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  nginx:
    build: ./nginx
    volumes:
      - ./static:/app/static
    ports:
      - "801:80"
      # - "443:443"
    depends_on:
      - app
      - web
    restart: "on-failure"

  web:
    build: . 
    volumes:
      - .:/app:rw 
      - static_volume:/app/static
    env_file:
      - .env
    # restart: "on-failure"


volumes:
  static_volume: